# Generated by Django 4.2.7 on 2026-01-06 07:45

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro_6', 'Pro 6 Months'), ('pro_9', 'Pro 9 Months'), ('pro_12', 'Pro 12 Months')], default='free', max_length=20)),
                ('plan_expiry', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationRuling',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('official_doc_url', models.URLField()),
                ('outcome_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTreeQuestion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('hierarchy', models.JSONField(default=list)),
                ('duty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('excise_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('required_certs', models.JSONField(default=list)),
                ('history', models.TextField(blank=True)),
                ('cis_hint', models.CharField(blank=True, max_length=500, null=True)),
                ('version_status', models.CharField(default='ACTIVE', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HS Code',
                'verbose_name_plural': 'HS Codes',
            },
        ),
        migrations.CreateModel(
            name='IncotermRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('recommendation_reason', models.TextField()),
                ('risk_transfer', models.TextField()),
                ('cost_responsibility', models.TextField()),
                ('best_for', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('hs_code', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('m2', 'Square Meter'), ('dona', 'Piece'), ('liter', 'Liter'), ('set', 'Set')], default='dona', max_length=20)),
                ('netto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('brutto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('package_type', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_alert', models.CharField(blank=True, max_length=500, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('required_certificates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Items',
            },
        ),
        migrations.CreateModel(
            name='TradeRouteOption',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('method', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('transit_time', models.CharField(max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=10)),
                ('message', models.TextField()),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='customs_api.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField()),
                ('required_documents', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_risk_analysis', to='customs_api.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('duty_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('savings_potential', models.CharField(max_length=100)),
                ('conditions', models.TextField()),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_tips', to='customs_api.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='HsCodePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('contract_number', models.CharField(max_length=100)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField()),
                ('partner_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('QORALAMA', 'Draft'), ('KUTILMOQDA', 'Pending'), ('TASDIQLANGAN', 'Approved'), ('RAD_ETILGAN', 'Rejected')], default='QORALAMA', max_length=20)),
                ('mode', models.CharField(choices=[('IM_40', 'IM-40 (Erkin muomala)'), ('IM_70', 'IM-70 (Bojxona ombori)'), ('IM_74', 'IM-74 (Bojxona hududida qayta ishlash)'), ('EK_10', 'EK-10 (Eksport)')], default='IM_40', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='declarations', to='customs_api.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL)),
                ('validation_issues', models.ManyToManyField(blank=True, to='customs_api.validationissue')),
            ],
            options={
                'verbose_name': 'Declaration',
                'verbose_name_plural': 'Declarations',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('diff', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('trend', models.CharField(default='stable', max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'code'],
                'unique_together': {('code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_thinking', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('customs_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('excise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='customs_api.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='customs_api.declaration')),
                ('issues', models.ManyToManyField(blank=True, to='customs_api.validationissue')),
            ],
        ),
    ]
