# Generated by Django 4.2.7 on 2026-01-06 12:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('PACKING_LIST', 'Packing List'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], max_length=20)),
                ('template_data', models.JSONField(default=dict)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HsCodePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('hierarchy', models.JSONField(default=list)),
                ('duty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('excise_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('required_certs', models.JSONField(default=list)),
                ('cis_hint', models.CharField(blank=True, max_length=500, null=True)),
                ('version_status', models.CharField(default='ACTIVE', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_code_passports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGeneration',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('PACKING_LIST', 'Packing List'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Contract'), ('CUSTOM', 'Custom')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('generated_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_generations', to='customs_api.usertemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField()),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
